#!/usr/bin/env bash

# colors
declare c_default='\033[0m'
declare c_red='\033[1;31m'
declare c_green='\033[1;32m'
declare c_yellow='\033[1;33m'
declare c_blue='\033[1;34m'

pfx_info="${c_green}[INFO] ${c_default}"
pfx_warn="${c_yellow}[WARN] ${c_default}"
pfx_error="${c_red}[ERROR]${c_default}"

# Usage: log [OPTIONS...] [MSG]
# Options:
#   -e  --error             Print an error message
#   -w  --warn,--warning    Print a warning message
#   -i  --info              Print an informative message
#   -t  --timestamp         Add timestamp to each log
function log() {
    msg_pfx=""
    timestamp=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -e | --error) msg_pfx="$pfx_error"; shift; ;;
            -w | --warn | --warning) msg_pfx="$pfx_warn"; shift; ;;
            -i | --info) msg_pfx="$pfx_info"; shift; ;;
            -t | --timestamp) timestamp="$(date '+%F %T')"; shift; ;;
            *) msg="$1"; shift; ;;
        esac
    done

    if [ -n "$msg_pfx" ]; then
        [[ -n "$timestamp" ]] && msg_pfx="${c_blue}[$timestamp]${c_default} $msg_pfx"
        echo -e "$msg_pfx $msg"
    fi
}

declare -a pacman_opts=(
  -S
  --needed
  --noconfirm
)

function configure_yay() {
  local yay_path='/usr/bin/yay'
  local aur_url='https://aur.archlinux.org/yay.git'

  log -i 'Install and configure yay'
  if [[ -f "$yay_path" ]]; then
    log -i 'yay is already installed'
    return 0
  fi

  log -i 'Clone yay'
  local tempdir
  tempdir="$(mktemp -d)"
  git clone -q "$aur_url" "$tempdir"

  if ! pushd "$tempdir"; then
    log -e "Failed to change directory to $tempdir";
    return 1;
  fi

  log -i 'Build and install yay'
  if ! makepkg -si --needed --noconfirm; then
    log -e 'Failed to build and install yay'
    return 1
  fi

  if ! popd "$tempdir"; then
    log -e "Failed to exit directory $tempdir"
    return 1
  fi

  rm -rf "$tempdir"

  log -i 'Copy pacman hooks'
  if ! sudo install -Dm 644 -t /etc/pacman.d/hooks ~/pacman_hooks/*.hook; then
    log -e 'Failed to copy pacman hooks'
    return 1
  fi

  local yayopts=(
    '--combinedupgrade'
    '--cleanmenu=false'
    '--diffmenu=false'
    '--editmenu=false'
    '--cleanafter=false'
  )
  log -i "Set yay options: ${yayopts[*]}"
  yay --save "${yayopts[@]}"
}

# TODO: Find a way to automatically download Sweet Cursors
function configure_icon_theme() {
  log -i "Configuring icon and cursor theme"

  log -i "Creating directories"
  icons_dir="$HOME/.icons"
  mkdir -pv "$icons_dir"

  log -w "Manually download Sweet Cursors from 'https://www.gnome-look.org/p/1393084' and enter the file path"
  read -r -p "Path to downloaded file (leave empty to skip): " archive_path

  if [ -n "$archive_path" ]; then
    log -i "Installing Sweet Cursors from archive $archive_path"
    tar -xvf "$archive_path" -C "$icons_dir"

    mkdir -pv "$icons_dir/default"
    ln -sfv "$icons_dir/Sweet-cursors/index.theme" "$icons_dir/default/index.theme"
  fi
}

function configure_gtk_theme() {
  local theme='Breeze-Dark'

  log -i "Changing Adwaita theme to $theme"
  "$HOME/bin/adwaita_theme.sh" -f -t "$theme"

  log -i 'Changing gtk-theme via gsettings'
  gsettings set org.gnome.desktop.interface gtk-theme "$theme"
  gsettings set org.gnome.desktop.interface color-scheme prefer-dark
}

function configure_sddm() {
  log -i "Enabling SSDM service"
  sudo systemctl enable sddm.service

  log -i "Changing SDDM theme background"
  sddm_themes_dir='/usr/share/sddm/themes'
  sudo install -Dm 644 ~/.background "$sddm_themes_dir/Backgrounds/Background.png"
  sudo sed -i "s/^Background=\(.*\)$/Background=\"Backgrounds/Background.png\"/g" "$sddm_themes_dir/Sugar-Candy/theme.conf"

  log -i "Copying SDDM config"
  sudo install -Dm 644 -t /etc/sddm.conf.d ~/sddm.conf.d/*
}

function configure_zsh() {
  zsh_custom_dir="${ZSH_CUSTOM:-/usr/share/oh-my-zsh/custom}"
  zsh_theme='powerlevel10k'
  zsh_plugins=('zsh-autosuggestions' 'zsh-syntax-highlighting' 'zsh-fzf-plugin')

  log -i "Installing ZSH theme '$zsh_theme' and plugins ${zsh_plugins[*]} to $zsh_custom_dir"
  sudo ln -sfv "/usr/share/zsh-theme-$zsh_theme" "$zsh_custom_dir/themes/$zsh_theme"
  for plugin in "${zsh_plugins[@]}"; do
    sudo ln -sfv "/usr/share/zsh/plugins/$plugin" "$zsh_custom_dir/plugins/$plugin"
  done

  log -i "Changing $USER's shell"
  sudo chsh -s /usr/bin/zsh "$USER"
}

function configure_vim() {
  log -i "Vim first run"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
}

function configure_docker() {
  log -i "Adding $USER to docker group"
  sudo usermod -aG docker "$USER"
}

function configure_services() {
  log -i "Starting vmware-networks-configuration service"
  sudo systemctl start vmware-networks-configuration.service

  log -i "Enabling and starting vmware-networks service"
  sudo systemctl enable --now vmware-networks.service

  log -i "Enabling and starting Vmware vmware-usbarbitrator"
  sudo systemctl enable --now vmware-usbarbitrator.service

  log -i "Enabling and starting pipewire service"
  systemctl --user enable --now pipewire

  log -i "Enabling and starting pipewire-pulse service"
  systemctl --user enable --now pipewire-pulse

  log -i "Enabling and starting bluetooth service"
  sudo systemctl enable --now bluetooth
}

function configure_x11() {
  log -i "Creating XDG user directories"
  xdg-user-dirs-update --force
}

function configure_env() {
  log -i 'Configuring /etc/environment'
  {
    echo "XDG_CONFIG_HOME=\"/home/$USER/.config\""
    echo "XDG_CACHE_HOME=\"/home/$USER/.cache\""
    echo "XDG_DATA_HOME=\"/home/$USER/.local/share\""
    echo "XDG_STATE_HOME=\"/home/$USER/.local/state\""
    echo
    echo 'XDG_DATA_DIRS="/usr/local/share:/usr/share"'
    echo 'XDG_CONFIG_DIRS="/etc/xdg"'
    echo
    echo 'ELECTRON_OZONE_PLATFORM_HINT=wayland'
    echo 'QT_QPA_PLATFORM=wayland'
    echo 'QT_QPA_PLATFORMTHEME=qt6ct'
  } | sudo tee -a /etc/environment
}

function configure_pam() {
  log -i 'Configure pam_gnome_keyring.so'

  declare pam_file=/etc/pam.d/login
  if grep -iq pam_gnome_keyring.so "$pam_file"; then
    log -i "pam_gnome_keyring.so is already in $pam_file"
    return
  fi

  {
    echo
    echo 'auth       optional     pam_gnome_keyring.so'
    echo 'session    optional     pam_gnome_keyring.so auto_start'
  } | sudo tee -a "$pam_file"
}

function configure_mnt() {
  log -i 'Creating common mount points'
  sudo mkdir -pv /mnt/{backup,sandisk,ssd500/{ntfs,btrfs}}

  log -i 'Setting ownership of ntfs/btrfs mount points'
  sudo chown -R "$USER:$USER" /mnt/ssd500/ntfs
  sudo chown -R "$USER:$USER" /mnt/ssd500/btrfs

  if [[ "$HOSTNAME" == 'tatooine' ]]; then
    log -i "Creating host ($HOSTNAME) specific mount points"
    sudo mkdir -pv /mnt/{localdisk,windows}

    log -i 'Setting ownership of ntfs/btrfs mount points'
    sudo chown -$ "$USER:$USER" /mnt/localdisk
    sudo chown -$ "$USER:$USER" /mnt/windows
  fi
}

function configure_fstab() {
  if [[ "$HOSTNAME" == 'tatooine' ]]; then
    log -i 'Appending auto-mounts to fstab'
    {
      echo
      echo '# 2 TiB Seagate'
      echo 'UUID=0698E25298E23FB3 /mnt/localdisk ntfs rw,relatime,nofail,exec,x-gvfs-show,uid=1000,gid=1000,umask=022 0 0'
    } | sudo tee -a /etc/fstab

    {
      echo
      echo '# Windows'
      echo 'UUID=4E023FFA023FE61D /mnt/windows   ntfs rw,relatime,nofail,exec,x-gvfs-show,uid=1000,gid=1000,umask=022 0 0'
    } | sudo tee -a /etc/fstab
  fi
}

function configure_spotify() {
  log -i 'Installing spotify via spotify-launcher'
  spotify-launcher -v --no-exec

  declare conf_file='/etc/spotify-launcher.conf'
  log -i "Editing $conf_file for wayland arguments"
  {
    echo
    echo 'extra_arguments = ["--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]'
  } | sudo tee -a /etc/spotify-launcher.conf
}

function configure_nvim() {
  log -i 'Cloning nvim configuration'
  git clone git@github.com:umtdg/nvim ~/.config/nvim
}

function configure_makepkg() {
  local target='/etc/makepkg.conf.d/makepkg.conf'

  log -i "Configure makepkg in $target"

  if [ -f "$target" ]; then
    log -i "Skipping as $target already exists"
    return 0
  fi

  mkdir -pv ~/build/{packages,sources,srcpkgdest}

  {
    echo '#!/hint/bash'
    echo "# Generated by $0"
    echo
    echo "PACKAGER='Umut Dag <umu7d9@gmail.com>'"
    echo "GPGKEY=7ACF523C6B63264D"
    echo 'PKGDEST=~/build/packages'
    echo 'SRCDEST=~/build/sources'
    echo 'SRCPKGDEST=~/build/srcpkgdest'
    echo
    echo 'BUILDENV+=(ccache)'
    echo
  } | sudo tee -a "$target"
}

# TODO: Add all config files for /etc, /usr, etc. under bootstrap

log -i 'Installing required packages'
sed '/^#/d;/^\s*$/d' packages.txt | sudo pacman "${pacman_opts[@]}" -

configure_makepkg

configure_yay

log -i 'Installing AUR packages'
sed '/^#/d;/^\s*$/d' packages.aur.txt | yay "${pacman_opts[@]}" -

configure_mnt
configure_fstab
configure_env
configure_pam
configure_services

configure_sddm
configure_icon_theme 
configure_gtk_theme 
configure_x11

configure_zsh
configure_vim
configure_docker

configure_spotify
configure_nvim

# vim: set filetype=bash sw=2 ts=2 sts=2 et:
