set -g default-command zsh
set -g default-terminal "tmux-256color"
set -g terminal-features 'xterm-256color:RGB'

set -g renumber-windows on
set -g history-limit 10000

set -g status-right ' #{?client_prefix,#[reverse]Locked#[noreverse] ,}"#{=21:pane_title}" %H:%M %d-%b-%y'

set -g focus-events on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Load tokyonight color scheme
source-file ~/.config/tmux/tokyonight-night.conf
