#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' run .#build

echo -e "${YELLOW}Switching...${NC}"
home-manager switch --flake .#$USER

echo -e "${GREEN}Switch to new generation complete!${NC}"
