#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Starting build...${NC}"
home-manager build --flake .#$USER

echo -e "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo -e "${GREEN}Building complete!${NC}"
